version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: // specify
      POSTGRES_PASSWORD: // specify
    ports:
      - "5433:5432"
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
  app:
    image: springmvc:0.0.1
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library
      SPRING_DATASOURCE_USERNAME: // specify
      SPRING_DATASOURCE_PASSWORD: // specify

volumes:
  my_postgres_data: