--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: book; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book (
    id integer NOT NULL,
    person_id integer,
    name character varying(100) NOT NULL,
    author_name character varying(100) NOT NULL,
    year integer NOT NULL,
    taken_at timestamp without time zone,
    CONSTRAINT book_year_check CHECK ((year > 0))
);


ALTER TABLE public.book OWNER TO postgres;

--
-- Name: book_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.book ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: person; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person (
    id integer NOT NULL,
    name character varying(70) NOT NULL,
    birthdate integer,
    CONSTRAINT person_birthdate_check CHECK ((birthdate > 1900))
);


ALTER TABLE public.person OWNER TO postgres;

--
-- Name: person_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: book; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.book (id, person_id, name, author_name, year, taken_at) FROM stdin;
3	\N	1984	George Orwell	1949	\N
5	\N	The Great Gatsby	F. Scott Fitzgerald	1925	\N
6	\N	Moby Dick	Herman Melville	1851	\N
8	\N	Pride and Prejudice	Jane Austen	1813	\N
9	\N	The Catcher in the Rye	J.D. Salinger	1951	\N
10	\N	The Hobbit	J.R.R. Tolkien	1937	\N
11	\N	Fahrenheit 451	Ray Bradbury	1953	\N
12	\N	Crime and Punishment	Fyodor Dostoevsky	1866	\N
13	\N	Brave New World	Aldous Huxley	1932	\N
14	\N	Jane Eyre	Charlotte Bront├л	1847	\N
15	\N	Wuthering Heights	Emily Bront├л	1847	\N
16	\N	The Divine Comedy	Dante Alighieri	1320	\N
17	\N	Les Mis├йrables	Victor Hugo	1862	\N
18	\N	The Brothers Karamazov	Fyodor Dostoevsky	1880	\N
19	\N	The Adventures of Huckleberry Finn	Mark Twain	1884	\N
20	\N	The Scarlet Letter	Nathaniel Hawthorne	1850	\N
21	\N	Dracula	Bram Stoker	1897	\N
22	\N	Frankenstein	Mary Shelley	1818	\N
23	\N	Great Expectations	Charles Dickens	1861	\N
24	\N	One Hundred Years of Solitude	Gabriel Garc├нa M├бrquez	1967	\N
25	\N	The Grapes of Wrath	John Steinbeck	1939	\N
26	\N	Anna Karenina	Leo Tolstoy	1877	\N
27	\N	The Picture of Dorian Gray	Oscar Wilde	1890	\N
28	\N	The Lord of the Rings	J.R.R. Tolkien	1954	\N
29	\N	Don Quixote	Miguel de Cervantes	1605	\N
30	\N	Ulysses	James Joyce	1922	\N
31	\N	Catch-22	Joseph Heller	1961	\N
32	\N	The Count of Monte Cristo	Alexandre Dumas	1844	\N
33	\N	The Sun Also Rises	Ernest Hemingway	1926	\N
34	\N	A Tale of Two Cities	Charles Dickens	1859	\N
35	\N	Heart of Darkness	Joseph Conrad	1899	\N
36	\N	Madame Bovary	Gustave Flaubert	1856	\N
37	\N	The Stranger	Albert Camus	1942	\N
38	\N	The Old Man and the Sea	Ernest Hemingway	1952	\N
39	\N	Lolita	Vladimir Nabokov	1955	\N
1	\N	Alice in Wonderland	John Collinson Smith	1964	\N
2	3	Alice in Wonderland	Luis Caroll	1964	2024-07-07 15:56:08.313
7	7	War and Peace	Leo Tolstoy	1869	2024-07-07 16:00:11.788
4	3	To Kill a Mockingbird	Harper Lee	1960	2024-07-07 16:02:42.067
40	\N	White Wolf	Jack London	1874	\N
\.


--
-- Data for Name: person; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.person (id, name, birthdate) FROM stdin;
3	Jane Doe	1913
4	Alice Johnson	1914
5	Bob Brown	1915
6	Charlie Davis	1916
7	David Evans	1917
8	Eva Foster	1918
9	George Green	1919
10	Hannah Hill	1920
11	Ivy Irving	1921
12	Jack James	1922
13	Kara King	1923
14	Liam Lee	1924
15	Mia Martin	1925
16	Noah Nelson	1926
17	Olivia Owens	1927
18	Paul Perry	1928
19	Quincy Quinn	1929
20	Rachel Ross	1930
21	Sam Smith	1931
22	Tina Turner	1932
23	Ursula Underwood	1933
24	Victor Vance	1934
25	Wendy White	1935
26	Xander Xavier	1936
27	Yara Young	1937
28	Zachary Zane	1938
29	Ada Allen	1939
30	Ben Bennett	1940
31	Clara Carter	1941
1	John Collinson	1912
\.


--
-- Name: book_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.book_id_seq', 40, true);


--
-- Name: person_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.person_id_seq', 31, true);


--
-- Name: book book_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_pkey PRIMARY KEY (id);


--
-- Name: person person_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_name_key UNIQUE (name);


--
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- Name: book book_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.person(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

